---
title: "Week 1 Notes - Course Introduction"
date: "2025-09-08"
---

## Key Concepts Learned
- Public Sector Data scinece has several considerations different from private sector
  - Public good, and equity consideration
  - Needs to be interpretable and not have algorithmic bias
- Git is for version control system (VCS)
- Github is the cloud computing backend of Git
- Github Lingo
  - Folder -> Repo
  - Commit -> Post a snapshot
  - Push means to send files to cloud
  - Pull downloads the files to local machine
- Setting up repositories on
- "YAML Ain't Markup Language"

## Coding Techniques
- Basics of tidyverse and its accompanying commands of filter(), select(), mutate(), and summarize()
- Quarto functions on how to **bold**, *italics*, ***both bold and italics***, `code list`, and ~~strikethrough~~ 
- Quarto uses --- as the header call
- "#" are used as the header calls
- Tibbles 
  - select() choose columns
  - filter() choose rows
  - mutate() create new variables 
  - summarize() calculate statistics 
  - group_by() operate on sub-groups
- Summarize and group_by tend ot happen together and typically using a pipeline %>%
- %>% pipelines are used to connect multiple codes in one command line rather than a sequence.

## Questions & Challenges
- Everything was clear. I would still like to mess around more with Quarto.
- I messed around with Quarto again @ 9/14/2025

## Connections to Policy
- This was a building block week, so not much of direct application rather tracking and documentation baseline for setup. 

## Reflection
- Learning how to create a custom repository was both enjoyable and insightful.
- It could also serve as a way to share supplementary analyses and to present code in a more public, graphical, and accessible format for non-coding audiences.
