project:
  type: website
  output-dir: docs

website:
  title: "Mohamad Al Abbas - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu: 
          - href: cv.qmd
            text: Curriculum Vitae
          - href: Publications.qmd
            text: Publications
      - text: In Class Labs
        menu: 
          - href: labs/lab_0/lab0_template.qmd
            text: "Week 0: dplyr Basics"
          - href: labs/week-03/scrips/week3_lab_exercise.qmd
            text: "Week 3: Data Visualization and EDA"
          - href: labs/week-04/scripts/week4_inclass_practice.qmd
            text: "Week 4: Spatial Operations with Pennsylvania Data"
      - text: Weekly Notes
        menu: 
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3
      - text: Assignments
        menu: 
          - href: Assignments/Assignment_1/assignment1_template.qmd
            text: "Assignment 1: Census Data Quality for Policy Decisions"
          - href: Assignments/Assignment_2/AlAbbas_Mohamad_Assignment2.qmd
            text: "Assignment 2: Healthcare Access and Equity in Pennsylvania"
      - text: Midterm
        menu: 
          - href: midterm/appendix/Midterm_2025.qmd
            text: "Technical Appendix"
          - href: midterm/slides/Midterm_slides_v3.qmd
            text: "Slides"
            
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
